[phases.setup]
nixPkgs = ['nodejs-18_x']

[phases.install]
cmds = [
  'npm ci --only=production --no-audit --no-fund --silent'
]

[phases.build]
cmds = ['echo "Skipping build step for faster deployment"']

[start]
cmd = 'npm start'
